### GET todos los productos
GET http://localhost:8989/products

### GET un producto por id
GET http://localhost:8989/products/1

### GET todos los productos de una categoría
GET http://localhost:8989/products?category=smartphones

### Crear un producto con POST
POST http://localhost:8989/products
Content-Type: application/json

{
    "sqlInjection": "DROP TABLE PRODUCTS",
    "id": 8,
    "title": "Microsoft Surface Laptop 4",
    "description": "Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.",
    "price": 1499,
    "discountPercentage": 10.23,
    "rating": 3,
    "stock": 68,
    "brand": "Microsoft Surface",
    "category": "laptops",
    "thumbnail": "https://cdn.dummyjson.com/product-images/8/thumbnail.jpg",
    "images": [
        "https://cdn.dummyjson.com/product-images/8/1.jpg",
        "https://cdn.dummyjson.com/product-images/8/2.jpg",
        "https://cdn.dummyjson.com/product-images/8/3.jpg",
        "https://cdn.dummyjson.com/product-images/8/4.jpg",
        "https://cdn.dummyjson.com/product-images/8/thumbnail.jpg"
    ]
}

### DELETE un producto por id
DELETE http://localhost:8989/products/6

### PATCH un producto por id
PATCH http://localhost:8989/products/2
Content-Type: application/json

{
  "year": 2022,
  "stock": 6,
  "images": [
    "https://cdn.dummyjson.com/product-images/2/1.jpg",
    "https://cdn.dummyjson.com/product-images/2/2.jpg",
    "https://cdn.dummyjson.com/product-images/2/thumbnail.jpg"
  ]
}